name: CustomWing
api: 4.8.1
version: 1.5
main: CustomWing\Main
author: Yukari
commands:
  customwing:
    description: "CustomWing"
    usage: /customwing
    permission: customwing.use
    aliases: [cw, wings]
permissions:
  customwing.use:
    default: true
